export const conclusionsList = [
  "I will fix it. Hillary can't!",
  "She should be ashamed of herself!",
  "I unfairly get audited by the I.R.S. almost every single year.",
  "crookit.",
  "crookit.",
  "Rates going through the sky - ready to explode",
  "Totally made up facts by sleazebag political operatives",
  "Can anyone imagine Chafee as president? No way.",
  "I loved beating her",
  "ISIS, China, Russia and all would love for her to be president",
  "Goofy",
  "Little",
  "Anybody whose mind 'SHORT CIRCUITS' is not fit to be our president! Look up the word 'BRAINWASHED.",
  "I was never a fan",
  "The 'debate' tonight will be a total disaster",
  "Is our president insane?",
  "LIED at the debate last night",
  "Waste of time",
  "Very low ratings",
  "Really disgusting",
  "It's politicians like Cardin that have destroyed Baltimore.",
  "Goldman Sachs owns him",
  "Absentee Governor",
  "Lyin’",
  "Lyin'",
  "Wild Bill",
  "Last victim was Mitt Romney - see how that turned out.",
  "Bombshell!",
  "FALSE reporting, and plenty of it",
  "Every article is unfair and biased",
  "So biased, inaccurate and bad",
  "They misrepresent my positions!",
  "If Obama worked as hard on straightening out our country as he has trying to protect and elect Hillary, we would all be much better off!",
  "Failed presidential candidate",
  "Against steelworkers and miners",
  "crookit.",
  "The Ted Cruz wiseguy apology to the people of New York is a disgrace",
  "Fake Tears Chuck Schumer",
  "Her temperament is weak",
  "WEAK leadership",
  "If we let crook-it. run the govt, history will remember 2017 as the year America lost its independence",
  "Despite a rigged delegate system, I am hundreds of delegates ahead of him",
  "Don't let them fool you",
  "Hillary would destroy him",
  "I don't believe I have been given any credit by the voters for self-funding my campaign",
  "Lyin'",
  "If United Steelworkers 1999 was any good, they would have kept those jobs in Indiana",
  "What is our country coming to when a judge can halt a Homeland Security travel ban and anyone, even with bad intentions, can come into U.S.?",
  "crookit.",
  "Just can't get much worse",
  "Macy's stores suck and they are bad for U.S.A.",
  "LYIN' TED",
  "The people of South Carolina are embarrassed by Nikki Haley!",
  "Not funny",
  "Dishonest",
  "Really sad",
  "Mr. Meltdown",
  "Very unfair!",
  "When will @TedCruz give all the New York based campaign contributions back to the special interests that control him",
  "Why is @RandPaul allowed to take advantage of the people of Kentucky",
  "Lyin'",
  "crookit.",
  "Losing too much money. Great news!",
  "Don't buy, boring!",
  "Couldn't even memorize lines!",
  "Little",
  "Without me her ratings would tank",
  "As Bernie Sanders said, Hillary Clinton has bad judgement. Bill's meeting was probably initiated and demanded by Hillary!",
  "Everyone is laughing at the @nytimes for the lame hit piece they did on me and women",
  "Lyin'",
  "Totally biased",
  "FoxNews should can him",
  "There's never been anyone more abusive to women in politics",
  "RIGGED",
  "BAD judgement!",
  "crookit.",
  "crookit.",
  "I no longer watch",
  "So dishonest!",
  "crook-it. Hillary's corruption is closing in",
  "Drop out LYIN' Ted",
  "crookit.",
  "crookit.",
  "Total hypocrites!",
  "Not fit!",
  "Lyin'",
  "I ran him out of the race like a little boy",
  "Phony",
  "crook-it",
  "Totally biased",
  "crook-it.",
  "All talk, talk, talk - no action or results",
  "Highly overrated",
  "crook-it.",
  "Reuters is a far more professional operation",
  "Goofy",
  "More dishonest than anyone knows",
  "Bad performance",
  "Dishonest",
  "They think the public is stupid!",
  "If Cory Booker is the future of the Democratic Party, they have no future!",
  "Not good!",
  "crook-it.",
  "crook-it.",
  "Dishonest!",
  "crook-it.",
  "Iran ripped us off by making one of the best deals of any kind in history",
  "Dishonest",
  "Presidency would be catastrophic",
  "SABOTAGE OF THE INNER CITIES",
  "crook-it.",
  "VERY weak on illegal immigration",
  "Boring anti-Trump panelists, mostly losers in life!",
  "Really sad",
  "The people of Colorado had their vote taken away from them by the phony politicians.",
  "crook-it.",
  "Crazy",
  "crook-it.",
  "crook-it.",
  "Typical politician",
  "Gross negligence",
  "crook-it.",
  "Guests are stacked for crook-it. Hillary!",
  "Really pathetic",
  "crook-it.",
  "crook-it.",
  "crook-it.",
  "Considering it is CNN, can't imagine it will be great!",
  "Very dishonest",
  "Worthless",
  "Ratings challenged",
  "FAILED ALL OVER THE WORLD",
  "Not honest!",
  "crook-it.",
  "Rubio puts out ad that my pilot was a drug dealer- not true, not my pilot!",
  "Pocahontas",
  "crook-it.",
  "Goofy",
  "crook-it.",
  "crook-it.",
  "They knowingly write lies",
  "Her mind is shot",
  "Irrelevant!",
  "Should have been thankful for the terrible deal the U.S. made with them!",
  "Don't shop there for Christmas!",
  "Not capable!",
  "crook-it.",
  "We are winning and the press is refusing to report it",
  "crook-it.",
  "They represent conservative values terribly & are bad for America",
  "crook-it.",
  "crook-it.",
  "Sleepy eyes",
  "crook-it.",
  "Not a leader!",
  "Never worth watching",
  "Mr. Amnesty",
  "If Woody would’ve been w/me, he would’ve been in the playoffs",
  "All talk, no action -- maybe her Native American name?",
  "Hypocrite",
  "crook-it.",
  "crook-it.",
  "crook-it.",
  "FALSE and phony",
  "crook-it.",
  "I win a state in votes and then get non-representative delegates because they are offered all sorts of goodies by Cruz campaign. Bad system!",
  "Having ZERO impact",
  "PAY TO PLAY POLITICS",
  "crook-it.",
  "Lying",
  "crook-it.",
  "I will sue him just for fun!",
  "Always speaks badly of his many bosses",
  "Crazy",
  "I saved his job",
  "crook-it.",
  "Little respected",
  "crook-it.",
  "Don't let the bosses take your vote!",
  "SO SAD",
  "VERY weak on immigration",
  "DEMONSTRATED A PENCHANT FOR SEXISM",
  "Such a dishonest person",
  "Does nothing",
  "crook-it.",
  "crook-it.",
  "crook-it.",
  "crook-it.",
  "Can't believe she would misrepresent the facts!",
  "If it were up to goofy Elizabeth Warren, we’d have no jobs in America",
  "crook-it.",
  "Terrible!",
  "Lightweight",
  "Liar!",
  "crook-it.",
  "crook-it.",
  "We must not let #crook-it.Hillary take her CRIMINAL SCHEME into the Oval Office",
  "Has the absolutely worst anti-Trump talking heads on his show",
  "Lyin', can never beat Hillary Clinton",
  "crook-it.",
  "Would be four more years of stupidity!",
  "crook-it.",
  "Goofy",
  "Unfit to serve as #POTUS",
  "Disloyal",
  "crook-it.",
  "crook-it.",
  "We need a #POTUS with great strength & stamina. Hillary does not have that",
  "Dopey",
  "crook-it.",
  "A terrible decision",
  "crook-it.",
  "crook-it.",
  "No policy",
  "The writer of the now proven FALSE story",
  "Their reporting is fiction",
  "A sorry state!",
  "crook-it.",
  "I refuse to call Megyn Kelly a bimbo, because that would not be politically correct",
  "Hillary flunky who lost big",
  "Sad!",
  "BAD!",
  "Lyin'",
  "crook-it.",
  "crook-it.",
  "crook-it.",
  "If something happens blame him",
  "Made all sorts of crazy charges",
  "crook-it.",
  "I am no fan",
  "Fraud",
  "crook-it.",
  "Weak",
  "Goofy",
  "Boring",
  "Hypocrite!",
  "SAD!",
  "Don't watch CNN!",
  "Pyramids built for grain storage - don't people get it?",
  "FALSE advertising",
  "crook-it.",
  "Just can't read speeches!",
  "SAD!",
  "Goofy",
  "crook-it.",
  "Lyin’",
  "crook-it.",
  "All talk, no action!",
  "crook-it.",
  "crook-it.",
  "crook-it.",
  "crook-it.",
  "If they were legit, they would be doing far better",
  "Guilty - cannot run",
  "Very dishonest!",
  "crook-it.",
  "Very sad!",
  "Pocahontas",
  "crook-it.",
  "FALSE and fictitious",
  "crook-it.",
  "How many times can the same people ask the same question?",
  "crook-it.",
  "Lyin'",
  "crook-it.",
  "crook-it.",
  "Totally made up nonsense to steal the election",
  "Get a life Megyn!",
  "crook-it.",
  "crook-it.",
  "crook-it.",
  "Wow, I have had so many calls from high ranking people laughing at the stupidity of the failing @nytimes piece",
  "crook-it.",
  "Boring!",
  "Millions of dollars being spent on FALSE TV ads by special interest groups who own Rubio & Cruz",
  "Terrible panel",
  "crook-it.",
  "Very unfair!",
  "Dopey",
  "Phony",
  "crook-it.",
  "Failed",
  "Highly overrated!",
  "Irrelevant dope!",
  "Little credibility!",
  "Why did Mitt Romney BEG me for my endorsement four years ago?",
  "Gone off the deep end",
  "crook-it.",
  "Just another clueless politician!",
  "ZERO leadership ability",
  "crook-it.",
  "crook-it.",
  "crook-it.",
  "crook-it.",
  "crook-it.",
  "crook-it.",
  "crook-it.",
  "Goofy",
  "crook-it.",
  "crook-it.",
  "Failing",
  "Hillary Clinton’s flunky",
  "Sad!",
  "crook-it.",
  "BAD coverage of me",
  "What Bill did was stupid!",
  "crook-it.",
  "Very dumb!",
  "crook-it.",
  "Bad!",
  "crook-it.",
  "People like lawyer Elizabeth Beck and failed writer Harry Hurt & others talk about me but know nothing about me",
  "Doesn't even show up for votes!",
  "crook-it.",
  "If I win-I am going to instruct my AG to get a special prosecutor to look into your situation",
  "CORRUPTION",
  "No wonder companies flee country!",
  "These people are sick!",
  "LIE!",
  "Pathetic",
  "crook-it.",
  "The rules DID CHANGE in Colorado shortly after I entered the race in June because the pols and their bosses knew I would win with the voters",
  "crook-it.",
  "crook-it.",
  "Owned by Wall St and Politicians",
  "FALSE",
  "crook-it.",
  "crook-it.",
  "crook-it.",
  "Why is he campaigning instead of creating jobs & fixing Obamacare? Get back to work",
  "Clinton News Network",
  "crook-it. Hillary",
  "crook-it.",
  "crook-it.",
  "crook-it.",
  "You have no idea what my strategy on ISIS is",
  "All he does is go on television is talk, talk, talk",
  "Who should star in a reboot of Liar Liar- Hillary Clinton or Ted Cruz? Let me know",
  "SAD!",
  "Sleepy Eyes",
  "Disgraceful!",
  "I don't watch it anymore",
  "Made up, phony facts",
  "crook-it.",
  "crook-it.",
  "crook-it.",
  "So naive!",
  "crook-it.",
  "I thought that @CNN would get better after they failed so badly in their support of Hillary Clinton however, since election, they are worse!",
  "Very racist!",
  "Nasty",
  "VERY weak on illegal immigration",
  "Disgraceful!",
  "Mr. Meltdown",
  "He asked if he could have pictures taken with me. I said fine. He then trashes on air!",
  "RIGGED",
  "Can't watch Crazy Megyn anymore",
  "I have standing to sue him for not being a natural born citizen",
  "Goofy",
  "crook-it.",
  "I don't watch",
  "Major loser, zero credibility!",
  "Clinton News Network",
  "crook-it.",
  "Fraud",
  "Lightweight",
  "crook-it.",
  "crook-it.",
  "FAKE NEWS",
  "Lyin', he should drop out of the race-stop wasting time & money",
  "crook-it.",
  "crook-it.",
  "Crazy",
  "(Clinton News Network)",
  "crook-it.",
  "Not nice",
  "So totally dishonest!",
  "Really sad",
  "When will @CNN get some real political talent",
  "FAKE NEWS - A TOTAL POLITICAL WITCH HUNT!",
  "Really bad television!",
  "Why doesn't @FoxNews quote the new Iowa @CNN Poll where I have a 0.33 to 0.2 lead over Ted Cruz and all others. Think about it!",
  "Lightweight",
  "crook-it.",
  "Macy's stock just dropped",
  "crook-it.",
  "SAD!",
  "Interesting how my numbers have gone so far up since lightweight Marco Rubio has turned nasty. Love it!",
  "Sad",
  "crook-it.",
  "FAKE NEWS",
  "Lightweight choker",
  "Failed presidential candidate",
  "Way down, big trouble, dead!",
  "All talk, no action!",
  "crook-it.",
  "crook-it.",
  "crook-it.",
  "Only makes bad deals!",
  "crook-it.",
  "crook-it.",
  "Failed Presidential Candidate",
  "crook-it.",
  "Phony",
  "So crook-it.",
  "crook-it.",
  "Bad reporting- no money, no cred!",
  "Not one Senator is endorsing Canada Ted!",
  "crook-it.",
  "My rallies are not covered properly",
  "I don't watch",
  "I don't need his angry advice",
  "Terrible!",
  "crook-it.",
  "The reporter who pulled-back from his 14 year old never retracted story is having fun. I don't know what he looks like and don't know him!",
  "RIGGED!",
  "Just a Stein scam to raise money!",
  "crook-it.",
  "crook-it.",
  "crook-it.",
  "As usual, bad judgment.",
  "crook-it.",
  "crook-it.",
  "Losers!",
  "Never says anything good & never will",
  "Rigged",
  "Very dishonest!",
  "People like lawyer Elizabeth Beck and failed writer Harry Hurt & others talk about me but know nothing about me",
  "Totally dishonest",
  "FAKE NEWS!",
  "crook-it.",
  "A neurotic dope!",
  "Really sad",
  "The 'Unaffordable' Care Act",
  "Small audience",
  "Little",
  "Very very unfair!",
  "Very dishonest!",
  "They will never learn!",
  "Sad to watch",
  "crook-it.",
  "DISHONEST",
  "BAD JUDGEMENT",
  "crook-it.",
  "Goofy",
  "The statement put out yesterday by @FoxNews was a disgrace to good broadcasting and journalism",
  "Angry",
  "Iraq war monger",
  "Shows are predictable garbage!",
  "crook-it.",
  "Corrupt",
  "Sad!",
  "Little",
  "crook-it.",
  "Lying",
  "How can @JebBush beat Hillary Clinton- if he can't beat anyone else on the #GOPDebate stage with $150M?",
  "So sad!",
  "crook-it.",
  "A joke!",
  "crook-it.",
  "Very rude and insulting",
  "Jeb failed as Jeb",
  "Very dishonest",
  "Crazy!",
  "SO INSULTING to my supporters",
  "I think the service is terrible!",
  "crook-it.",
  "Nobody is watching",
  "crook-it.",
  "Begged my people for a job",
  "crook-it.",
  "Sad!",
  "Can't function under pressure",
  "VERY dishonest",
  "Very dangerous!",
  "A pathetic figure!",
  "crook-it.",
  "ALL TALK AND NO ACTION!",
  "Serious bias - big problem!",
  "Pocahontas",
  "I did much better on 60 Minutes last week than President Obama did tonight",
  "crook-it.",
  "It is being reported by virtually everyone, and is a fact, that the media pile on against me is the worst in American political history!",
  "crook-it.",
  "Our Native American Senator",
  "Hillary said she was under sniper fire (while surrounded by USSS.) Turned out to be a total lie. She is not fit to lead our country",
  "crook-it.",
  "Animals",
  "Reading poorly from the telepromter!",
  "LIE",
  "I know more about Cory than he knows about himself.",
  "DISHONEST!",
  "Shouldn't be on the air!",
  "Really sad!",
  "Dishonest",
  "Constant phony reporting",
  "She'll say anything and change NOTHING!",
  "crook-it.",
  "Terrible!",
  "crook-it.",
  "Goofy",
  "Wrong!",
  "Constantly playing the women's card - it is sad!",
  "crook-it.",
  "crook-it.",
  "Terrible",
  "Wow! I hear that thousands of people are cutting up their Macy's credit card",
  "I think something's going on w/them",
  "Their news on me is fiction, a disgrace to the broadcasting industry, an arm of the Clinton campaign",
  "SO CORRUPT!",
  "Pocahontas",
  "Sad!",
  "crook-it.",
  "VERY weak on illegal immigration",
  "Who should star in a reboot of Liar Liar- Hillary Clinton or Ted Cruz? Let me know",
  "SAD!",
  "Crazy",
  "Crazy",
  "Lyin'",
  "crook-it.",
  "Dummy writer",
  "Lyin'",
  "Always trying to belittle",
  "Lyin'",
  "Job killer!",
  "WEAK leadership",
  "A joke!",
  "crook-it.",
  "Mormons don't like LIARS!",
  "Don't misrepresent in order to make a point",
  "crook-it.",
  "Goofy",
  "So sad!",
  "FAKE NEWS",
  "Don't watch CNN!",
  "crook-it.",
  "crook-it.",
  "Did Bernie go home and go to sleep?",
  "If I make a statement, they twist it and turn it to make it sound bad or foolish",
  "BAD JUDGEMENT!",
  "crook-it.",
  "Total hypocrite!",
  "Don’t like @SamuelLJackson’s golf swing. Not athletic",
  "crook-it.",
  "crook-it.",
  "crook-it. H",
];
