export const enemiesList = [
  "Chuck Jones",
  "Tom Llamas",
  "Gonzalo P. Curiel",
  "U.S. leaders",
  "Republican Party",
  "The Obama administration",
  "Washington insiders",
  "Scott Walker",
  "“Meet the Press”",
  "The Weekly Standard",
  "Politicians",
  "Tony Schwartz",
  "Cokie Roberts",
  "Bandon Dunes Golf Resort",
  "Common Core standards",
  "The Daily Beast",
  "Charles Lane",
  "United Nations",
  "Frank Bruni",
  "James Robart",
  "Brandon Victor Dixon",
  "Anthony D. Weiner",
  "Ben Cardin",
  "Marco Rubio",
  "The Fox News debate",
  "Obamacare",
  "Kasie Hunt",
  "Univision",
  "Erick Erickson",
  "Rich Lowry",
  "European leaders",
  "Sopan Deb",
  "John Lewis",
  "Leaked D.N.C. emails",
  "John King",
  "Bernie Sanders",
  "Michael J. Morell",
  "Joe McQuaid",
  "Islamic State",
  "Jeb Bush supporters",
  "Rick Perry",
  "John R. Allen",
  "Ronda Rousey",
  "Harry Hurt III",
  "Ted Cruz",
  "The New York Times",
  "The Bill, Hillary and Chelsea Clinton Foundation",
  "Charles Krauthammer",
  "Stephanie Rawlings-Blake",
  "The Huffington Post",
  "Rick Scott",
  "“Rockin’ in the Free World”",
  "Jeff Flake",
  "“The Triumph of William McKinley”",
  "Jeb Bush campaign staffer",
  "Charles Blow",
  "A podium in the Oval Office",
  "Club for Growth",
  "Iran",
  "Jeb Bush",
  "United States",
  "Lawrence O'Donnell",
  "Tom Ridge",
  "John Oliver",
  "Illegal immigration",
  "Robert Gates",
  "Anderson Cooper",
  "Frank Luntz",
  "Juan Williams",
  "Errol Louis",
  "Jeff Horwitz",
  "Vandals",
  "Joseph R. Biden Jr.",
  "Cheri Jacobus",
  "National Review",
  "Ted Cruz campaign",
  "Bobby Jindal",
  "Mexico",
  "Michael Bloomberg",
  "Other Republican candidates",
  "Martin O'Malley",
  "Colin Powell",
  "George Pataki",
  "Ted Cruz’s Iowa caucus speech",
  "Sam Liccardo",
  "Lindsey Graham",
  "Republican Party of Virginia",
  "Tim O'Brien",
  "Glenn Beck",
  "The Cruz-Kasich pact",
  "“Inside Politics”",
  "George Will",
  "Fox News polls",
  "Dan Henninger",
  "Charles Koch",
  "Rand Paul",
  "Paul D. Ryan",
  "Molly Sims",
  "Jennifer Rubin",
  "Anderson Cooper “360”",
  "Macy's",
  "Nikki Haley",
  "John Legere",
  "Brent Bozell",
  "Microphone at the first presidential debate",
  "Penn Jillette",
  "NBC News",
  "Tavis Smiley",
  "Debbie Wasserman Schultz",
  "Mort Zuckerman",
  "Ben Carson",
  "Voters",
  "Donald Trump opposition",
  "“The Bias-Free Language Guide”",
  "The State of the Union address",
  "Clare O'Connor",
  "Chris Christie",
  "Paulina Vega",
  "Willie Geist",
  "Democratic presidential candidates",
  "Vanity Fair",
  "Lincoln Chafee",
  "“The Last Word with Lawrence O'Donnell”",
  "Republicans",
  "Russell Moore",
  "Graydon Carter",
  "Paul Begala",
  "Pundits",
  "Shep Smith",
  "Bernard Goldberg",
  "Bill and Hillary Clinton",
  "Democratic National Convention",
  "“TODAY”",
  "New York Daily News",
  "“Super PACs”",
  "Chuck Schumer",
  "United Steelworkers Local 1999",
  "T-Mobile",
  "Hallie Jackson",
  "ABC News Politics",
  "Jeb Bush campaign",
  "Hugh Hewitt",
  "Television commercials",
  "Mark Cuban",
  "Alwaleed bin Talal",
  "Chuck Todd",
  "Protesters",
  "Political ads in Indiana",
  "Ruth Bader Ginsburg",
  "Germany",
  "The Wall Street Journal",
  "U.S. trade pacts",
  "Major Garrett",
  "Court order halting immigration ban",
  "The American delegate system",
  "The 2016 election",
  "Dana Perino",
  "North American Free Trade Agreement",
  "Ruth Marcus",
  "“The View”",
  "President Obama",
  "The Wall Street Journal editorial board",
  "Katy Tur",
  "Bakari Sellers",
  "Jeff Zeleny",
  "The cast of “Hamilton”",
  "Arianna Huffington",
  "Carly Fiorina",
  "Maureen Dowd",
  "Katie Couric",
  "The United States government",
  "Other presidential candidates",
  "NBC",
  "John Harwood",
  "Mark Halperin",
  "Jeff Zucker",
  "John Roberts",
  "The Republican establishment",
  "John Kasich's ad guy",
  "Republican National Committee",
  "John Kasich",
  "Rodrigo Duterte",
  "New Jersey",
  "Mary Katharine Ham",
  "“World News Tonight”",
  "United States employment situation",
  "Fox News",
  "The electoral process",
  "Samuel L. Jackson",
  "Jonathan Martin",
  "Ben Schreckinger",
  "Assault allegations",
  "Meryl Streep",
  "Chris Stirewalt",
  "“Saturday Night Live”",
  "The Des Moines Register",
  "Michael Nutter",
  "Ana Navarro",
  "The “mainstream” media",
  "Whoopi Goldberg",
  "Michael Barbaro",
  "Major League Baseball",
  "Saudi Arabia",
  "Elizabeth Pocahontas Warren",
  "Elizabeth Warren",
  "Election pollsters",
  "Brit Hume",
  "The Associated Press",
  "Serge Kovaleski",
  "Debates",
  "U.S. visa system",
  "Matt Bai",
  "ABC News-Washington Post poll",
  "Alec Baldwin",
  "U.S.-Mexico border",
  "“The O'Reilly Factor”",
  "Rick Wilson",
  "Washington, D.C.",
  "Special interests",
  "New York Times articles",
  "Mitt Romney",
  "Bill Kristol",
  "Meghan McCain",
  "Vote recount in Wisconsin",
  "Transportation Security Administration",
  "Neil Young",
  "Investigation of Hillary Clinton's email",
  "“Morning Joe”",
  "Stuart Stevens",
  "Cory Booker",
  "Marty Walsh",
  "The Rexnord Corporation",
  "CNN",
  "USA Today",
  "All Business: The Essential Donald Trump",
  "David Gregory",
  "Forbes",
  "Huma Abedin",
  "Ben Sasse",
  "Politico",
  "Amy Chozick",
  "Britain",
  "Barbara Res",
  "Arnold Schwarzenegger",
  "Mika Brzezinski",
  "Woody Johnson",
  "John Sununu",
  "Bob Vander Plaats",
  "The Democratic debate",
  "Donny Deutsch",
  "North Atlantic Treaty Organization",
  "Veterans Affairs",
  "Tim Kaine",
  "Hillary Clinton",
  "Recount effort in Pennsylvania",
  "Trump/Russia report",
  "John O. Brennan",
  "‘Politically correct fools’",
  "Joy Behar",
  "Internal Revenue Service",
  "Democrats",
  "Alisyn Camerota",
  "Super Bowl 50",
  "Paul Singer",
  "Bill de Blasio",
  "Fortune",
  "“NBC Nightly News”",
  "Wall Street Journal-NBC News poll",
  "Early voting in Florida",
  "Megyn Kelly",
  "The Benghazi hearings",
  "Melinda Henneberger",
  "The Iran nuclear deal",
  "The New Hampshire Union Leader",
  "Amazon",
  "The Washington Post",
  "Lockheed Martin F-35 Program",
  "S.E. Cupp",
  "New 747 Air Force One",
  "John McCain",
  "Steve Rattner",
  "Frank VanderSloot",
  "Lisa Belkin",
  "Donna Brazile",
  "Nicolle Wallace",
  "Karl Rove",
  "RedState.com",
  "Democratic National Committee",
  "Angela Merkel",
  "CNBC",
  "The public",
  "Republican presidential candidates",
  "Don Lemon",
  "“New Day”",
  "Trans-Pacific Partnership",
  "David Brooks",
  "George W. Bush",
  "Alicia Machado",
  "Carl Cameron",
  "Elizabeth Beck",
  "George Bush",
  "Joe Scarborough",
  "“Hamilton”",
  "Marc Thiessen",
  "China",
  "Maggie Haberman",
  "CNN panelists",
  "Bill Clinton",
];
