export const insultsList = [
  "failing",
  "a total waste of money",
  "didn't get the right gene",
  "has made so many mistakes",
  "so negative, getting even worse",
  "sick",
  "softball questions",
  "very bad at math",
  "not fit to be our next president!",
  "not good",
  "a total #Mediafraud",
  "want me out of the race so badly",
  "had zero in his presidential run before dropping out in disgrace",
  "stupid",
  "uncomfortable looking",
  "has made serious bad calls",
  "incompetent",
  "will lead to at least partial world destruction",
  "failed at the border",
  "a terrible representative of Evangelicals",
  "a DISASTER on foreign policy",
  "should be immediately disqualified in Iowa",
  "killed jobs!",
  "hypocrite",
  "big loser",
  "refuses to talk about the three new national polls that have me in first place",
  "sellng out America",
  "not funny",
  "did a really bad job as Governor of California and even worse on the Apprentice",
  "dishonest reporting",
  "very stupid use of e-mails",
  "inept",
  "clown",
  "weak on illegal immigration",
  "total mess",
  "failing",
  "just got contact lenses and got rid of the glasses. He wants to look cool, but it's far too late",
  "record is so bad, unable to answer tough questions!",
  "he would be so easy to beat!",
  "failed all over the world",
  "has no clue",
  "lies so much and is so dishonest",
  "so easy to beat!",
  "small crowds",
  "horrendous",
  "wants to take in as many Syrians as possible",
  "fake news, just like the CNN, ABC, NBC polls in the election",
  "a CRIMINAL ENTERPRISE",
  "ratings starved",
  "we are being led to slaughter",
  "pandering to the worst instincts in our society",
  "a foreign policy DISASTER",
  "if @amazon ever had to pay fair taxes, its stock would crash and it would crumble like a paper bag",
  "disgrace",
  "loves to write badly about me",
  "one of the dumbest of all pundits",
  "sad & irrelevant!",
  "almost everybody quitting",
  "the author of the now discredited @nytimes hit piece on me",
  "no credibility",
  "viewers & ratings are way down",
  "a disaster",
  "spent $430 million and lost ALL races",
  "no longer a credible source",
  "not our friend",
  "hard to watch, zero talent",
  "is a catastrophe",
  "not very good or professional",
  "dumb as a rock",
  "a lightweight choker",
  "ineffective",
  "why did he accept money from people who espouse gay marriage?",
  "rather viciously firing all of its 300 workers",
  "always tough when they falsify",
  "lying",
  "seriously failing",
  "biased",
  "an all talk, no action dummy!",
  "always a complete hit job",
  "really one-sided and unfair reporting",
  "have got to stop working to be so politically correct",
  "waste of time",
  "a dope!",
  "her record is so bad",
  "love watching him fail",
  "lightweight",
  "looks and sounds so ridiculous",
  "in bed w/ Wall St.",
  "she wanted to breast pump in front of me at dep.",
  "very foul mouthed",
  "the worst of NBC",
  "liar",
  "ridiculous",
  "very stupid, highly incompetent people running our country into the ground",
  "out negotiated again",
  "failed @CNN announcer",
  "poor, pathetic people",
  "incompetent",
  "doubled Florida State debt",
  "despite the[ir] best efforts, the people are speaking loudly and clearly",
  "a basket case",
  "should be ashamed of yourself",
  "wrong on so many subjects",
  "not TRUE to himself",
  "no sense of markets",
  "in turmoil",
  "not believable",
  "the most corrupt person to ever run for the presidency of the United States",
  "if Jeb Bush were more competent he could not have lost the skirmish with Marco",
  "low ratings",
  "a nervous wreck",
  "pathetic",
  "didn’t have the guts to run for POTUS",
  "has no power",
  "looks more and more like a paper tiger",
  "not a talented person or politician",
  "a fraud!",
  "failed @NBC and he is now failing @CNN",
  "a joke!",
  "they aren't worthy of representing the great people of NH",
  "thugs",
  "led Obama into bad decisions!",
  "bad",
  "low energy",
  "the lightweight no show Senator from Florida",
  "has not covered my long-shot great finish in Iowa fairly",
  "exhausted",
  "the only network that does not even mention my very successful event last night",
  "failing",
  "failed presidential candidate",
  "will never MAKE AMERICA GREAT AGAIN!",
  "very dumb",
  "incompetent",
  "arrogant",
  "so easy to beat!",
  "dying",
  "is closing in on being the dumbest of them all",
  "made up events THAT NEVER HAPPENED",
  "[one] of the dumbest people in politics",
  "loser",
  "desperate and sad",
  "resign!",
  "a total phony",
  "should get a life",
  "my worst Miss U.",
  "an establishment dope",
  "dishonest guy",
  "knows nothing about me or my religion",
  "rigged",
  "incompetent",
  "lowlife!",
  "unfit to serve",
  "massive deficit, bad jobs forecast, a mess",
  "should focus on fair and balanced reporting",
  "anchors are completely out of touch with everyday people",
  "wasted $400 million",
  "crooked",
  "disastrous judgment",
  "pushed strongly by the media and the Clinton Campaign",
  "has zero credibility",
  "registers ZERO in the polls",
  "neurotic",
  "rigged",
  "afraid of Obama & the emails",
  "phony",
  "said she is used to dealing with men who get off the reservation. Actually, she has done poorly with such men!",
  "just doesn't know about winning",
  "mess!",
  "desperate to distract from Clinton's anti-2A stance",
  "almost last",
  "a TRUE lowlife pol!",
  "overrated",
  "weak",
  "can't win",
  "be smart and win for a change",
  "thugs",
  "wrote yet another hit piece on me",
  "got swamped (or destroyed) by comparison",
  "by far the weakest of the lot",
  "know NOTHING",
  "phony",
  "poor and purposely inaccurate reporting",
  "caught cold in lie",
  "dummy",
  "an incompetent judge!",
  "would be a disaster",
  "weak on illegal immigration",
  "highly overrated",
  "can't even get a Senator like @BenSasse, who is easy, to endorse him",
  "where did you find that dumb panel",
  "totally in the Hillary circle of bias",
  "childishly written & taunting PR statement",
  "does nothing to help!",
  "hypocrite",
  "failing",
  "not going to watch anymore",
  "probably the worst Mayor in the history of #NYC",
  "put it to sleep",
  "lightweight",
  "very weak on illegal immigration",
  "failing",
  "nothing works",
  "weak candidate",
  "registered at less than 1 percent in the polls",
  "chances of winning are zero",
  "failed candidate",
  "has a career that is totally based on a lie",
  "campaign is in total disarray",
  "impersonation just can't get any worse",
  "fake!",
  "really dumb",
  "a typical politician",
  "dummy writer",
  "will be a disaster for jobs and the economy!",
  "paid ridiculous amounts of money",
  "clueless",
  "really boring, slow, lethargic",
  "few people are watching",
  "disloyal",
  "has made so many mistakes",
  "has a major inferiority complex",
  "doesn't know how to win",
  "total disaster",
  "never had the guts to run for president",
  "credibility will soon be gone!",
  "we are weak",
  "insane",
  "dead network!",
  "really pathetic",
  "no ratings",
  "inaccurate",
  "totally unfair!",
  "biggest liar in politics!",
  "easy to beat!",
  "you have failed, failed, and failed",
  "no strength or stamina",
  "it's the Democrat's total weakness that is the greatest recruiting tool of ISIS!!!",
  "failing",
  "inaccurate stories",
  "highly neurotic",
  "knows nothing about me",
  "lightweight reporter",
  "failing",
  "zero imagination and even less stamina",
  "dying",
  "failing",
  "poor leadership skills",
  "just totally bombed",
  "unfunny show",
  "fraud",
  "a disaster - as I've been saying from the beginning",
  "bad reporting",
  "rigged",
  "cast is terrible",
  "a running mate who was unable to catch on in her own failed campaign",
  "sleepy eyes",
  "should spend more time on fixing and helping his district, which is in horrible shape and falling apart",
  "horrible disaster",
  "only knows how to make a speech when it is a hit on me",
  "total dud",
  "unfit to serve as President",
  "really boring",
  "playing with fire",
  "cannot be President",
  "ill-fit",
  "no energy left!",
  "all talk and no action",
  "cratered",
  "no guts no glory",
  "came out with another one of their phony polls",
  "1 fabricated",
  "has BAD JUDGEMENT",
  "shouldn't be allowed to do [his] bias commentary",
  "came to my office looking for work",
  "may be the most corrupt person ever to seek the presidency",
  "did a terrible job",
  "crazy",
  "irrelevant",
  "very weak on stopping illegal immigration",
  "why don't you have some knowledgeable talking heads on your show for a change",
  "badly defeated & demoralized",
  "dummies",
  "embarrassed himself with his failed run for President",
  "says one thing for money, does another for votes",
  "gave up and enlisted Mommy and his brother",
  "he thinks he would have won against me. He should say that but I say NO WAY!",
  "off the rails",
  "some of the dumbest people on television work for the Wall Street Journal",
  "hollowing out our military",
  "has one of the worst reporters in the business",
  "a total disaster for Republicans & America",
  "loser",
  "made a fool of himself",
  "rigged",
  "other networks seem to treat me so much better than Fox News",
  "dishonest reporting",
  "failing for 30 years",
  "totally biased",
  "just plain dumb!",
  "so negative it is impossible to watch",
  "very few people read",
  "wanted to do a second book with me for years (I said no)",
  "really bad judgement and a temperament",
  "how will the media put a negative spin on this one?",
  "dishonest",
  "one of the dumber pundits on tv",
  "weak",
  "dummy dope",
  "sad",
  "rigging election!",
  "failing",
  "failing",
  "a nervous wreck",
  "sloppy",
  "still not nice",
  "did a terrible job against me",
  "poses a direct national security threat",
  "worst voting record in Senate",
  "a disaster!",
  "failing",
  "too much debt and not enough viewers",
  "not nice!",
  "had to bring in mommy to take a slap at me",
  "coverage this morning of the very average Clinton speech and Convention is a joke",
  "corruption and incompetence",
  "have made U.S. a mess!",
  "the books are cooked",
  "a con",
  "not only breaking the spirit of the law but the law itself",
  "bad on women's health issues",
  "very weak on illegal immigration",
  "purposely mischaracterized my statement",
  "paid for by the politicians bosses",
  "blew an election that should have never been lost",
  "he is scamming Florida",
  "dopes",
  "only Fox News is consistantly fighting the Trump win",
  "couldn't be elected dog catcher if he ran again",
  "lost an election that should have easily been won",
  "just gave a disastrous news conference",
  "did not list on his personal disclosure form personally guaranteed loans from banks. They own him!",
  "disaster",
  "no talent",
  "bad reporters",
  "a total disaster!",
  "failing",
  "has no credibility",
  "trying to extort $1,000,000.00 from me",
  "really bad",
  "ran Red State into the ground",
  "terrible (and boring)",
  "not presidential material",
  "failing",
  "it is dead",
  "another phony hit job on me",
  "establishment flunky",
  "the worst president in U.S. history!",
  "worst mayor in the United States",
  "money losing",
  "corrupt",
  "one of the dumbest & most dangerous misjudgments ever",
  "we are letting criminals knowingly stay in our country",
  "in the tank for Clinton",
  "has done a terrible job representing workers",
  "irrelevant",
  "a Wall Street PUPPET!",
  "failed advisor",
  "doesn't have the strength or the stamina to MAKE AMERICA GREAT AGAIN!",
  "lied",
  "pathetic",
  "weak",
  "lightweight",
  "she looked lost",
  "her bad show is a total hit piece on me",
  "so wrong, so often",
  "bought and paid for by lobbyists!",
  "sad!",
  "low energy",
  "fictitious polling numbers",
  "cheats",
  "1 owned by her donors",
  "if you listen to Carly Fiorina for more than ten minutes straight, you develop a massive headache",
  "very disloyal",
  "could not stop Obama (twice)",
  "come at you from all sides",
  "always fighting the Republican nominee!",
  "has made so many mistakes",
  "too much staff being paid way too much money",
  "rigged!",
  "dying",
  "a failing campaign",
  "sadly weak on immigration",
  "truly stupid",
  "so irrelevant to the race",
  "dishonest lightweight",
  "just the beginning & it's going to get worse",
  "he's bottom (and gone), I'm top (by a lot)",
  "will never be able to beat Hillary",
  "covers me more inaccurately than any other media source",
  "a major national security risk",
  "failed magazine",
  "using race-baiting",
  "dopey",
  "doing a lousy job in taking care of our Vets",
  "at the back of the pack",
  "rapidly fading",
  "using the oldest play in the Dem playbook",
  "newspaper of fiction",
  "deeply troubled",
  "one of the worst presidential candidates in history",
  "dead on arrival!",
  "is so embarrassed by their total -1 support of Hillary Clinton",
  "they only write bad stories about me!",
  "reckless",
  "doing really badly",
  "would be nice if @jmartNYT learned how to read the polls before writing his next story",
  "they 'racial profile' all over the place",
  "arrogant",
  "has been run into the ground",
  "bleeding red ink",
  "weak on border security",
  "truly one of the worst newspapers",
  "desperate",
  "wrote a failed book",
  "spending all of his time in NH",
  "nasty",
  "totally biased",
  "really went wacko today",
  "so dishonest",
  "hypocrite",
  "racists",
  "don't even call us anymore",
  "over",
  "one of the most incompetent ever made",
  "one of the all time great enablers!",
  "tried to extort $1,000,000 from me",
  "they don't have a clue!",
  "decades of lies and scandal",
  "all talk & no action",
  "has gone really hostile ever since I said I won't do or watch the show anymore",
  "they lie",
  "should not be allowed to run for president",
  "so ridiculous",
  "dummies",
  "will do anything to stay at the trough",
  "dishonest",
  "bad judgement",
  "failing",
  "endorsed a candidate who can't win",
  "sad",
  "has totally sold out",
  "bad reporting",
  "bad",
  "just can't go on any longer",
  "selfishly opposed to me!",
  "bad, dishonest journlists",
  "irrelevant clown, sweats and shakes nervously",
  "covers me very inaccurately",
  "a TOTAL FABRICATION",
  "fortunately they have bad ratings",
  "biased",
  "a total joke, and everyone knows it!",
  "failed presidential candidate",
  "an embarrassed loser",
  "dishonest",
  "they don't know what to do",
  "all talk and no action",
  "a very dishonest group",
  "crazy",
  "so FALSE and angry",
  "a clown!",
  "one of the dumber people on television",
  "failed badly in his fight against ISIS",
  "weak and totally conflicted",
  "bought and paid for by special interests!",
  "totally ineffective",
  "laughable!",
  "willing to say anything",
  "dishonest",
  "incompetent",
  "controlled by Mexican government?",
  "crooked",
  "has no chance",
  "a world class LIAR",
  "lies",
  "will find a good spinnnn!",
  "incompetent",
  "highly overrated",
  "totally corrupt gov't",
  "all talk, no action",
  "terrible, failed badly",
  "a @FoxNews flunky",
  "a joke!",
  "easy for me to beat",
  "weak",
  "cheating Bernie out of the nom",
  "forgot to mention my phenomenal biz success rate",
  "a dying newspaper",
  "campaign is dead",
  "totally phoney",
  "truly one of the dumbest of the talking heads",
  "she will never make it on T.V.",
  "little",
  "weak leaders",
  "failing",
  "totally lost control of illegal immigration, even with criminals",
  "dummy",
  "a joke",
  "failed career",
  "disaster",
  "failing",
  "is lying when he says his disruptors aren't told to go to my events. Be careful Bernie, or my supporters will go to yours!",
  "failing",
  "cannot report the news truthfully",
  "phony Native American heritage",
  "still thinks Romney won",
  "lost all credibility",
  "really bombed tonight",
  "sad",
  "fraud!",
  "can't close the deal with Bernie Sanders",
  "dumb",
  "looks like a tabloid",
  "betrayed Bernie voters",
  "dummy",
  "gave amnesty to criminal aliens guilty of 'sex offenses.' DISGRACE!",
  "doesn't know much'",
  "should be fired",
  "so many people calling to say they are cutting up their Macy's credit card",
  "bought and paid for by lobbyists!",
  "will be gone soon",
  "won't report!",
  "one of the worst reporters in the business",
  "too much failure in office",
  "dumb as a rock",
  "one of the worst-performing stocks",
  "failing",
  "dumb, one-sided panels",
  "only says negative",
  "worst record",
  "unwatchable!",
  "dishonest",
  "a V.P. candidate who failed badly",
  "sent out a VOTER VIOLATION certificate to thousands of voters",
  "just another dishonest politician",
  "tax scam",
  "absolutely disgraceful",
  "should have gone to Louisiana days ago, instead of golfing. Too little, too late!",
  "got zero against me- no cred!",
  "put our country in such peril",
  "hardly knows me",
  "should be forced to take an IQ test",
  "fired like a dog",
  "a real dummy",
  "dishonest reporting",
  "bad judgement and temperament",
  "destroyed jobs and manufacturing",
  "now irrelevant",
  "one-sided",
  "total agenda",
  "puts the plane behind her like I have been doing from the beginning",
  "fraudulent editing",
  "just write whatever they want to write, making up sources along the way!",
  "not a natural deal maker",
  "he will fall like all others",
  "failed on the border",
  "lying on so many levels",
  "disloyal",
  "nasty!",
  "dumb as a rock",
  "did really poorly on television",
  "a complete disaster",
  "were so wrong",
  "if he can't manage his campaign, how can he manage our countries finances?",
  "judgement so bad",
  "will NEVER Make America Great Again",
  "goofy",
  "not looking tough!",
  "a disaster candidate who had no guts and choked",
  "no credibility",
  "sick",
  "horrible",
  "a sad case",
  "couldn't even respond properly to President Obama's State of the Union Speech without pouring sweat & chugging water",
  "has a horrible attitude",
  "weak and ineffective",
  "focus on running your company",
  "bad!",
  "phony",
  "really weird, she's being driven crazy",
  "boring and biased!",
  "disgraceful behavior",
  "should resign",
  "a low-class slob",
  "totally lost",
  "did poorly last night in the debate",
  "ridiculous",
  "looks like a little boy on stage",
  "not presidential material",
  "going through massive attacks to its people by the migrants allowed to enter the country",
  "fell more than anybody",
  "complaints about them are at a 15 year high",
  "1 CONTROLLED",
  "chokes on the truth",
  "dishonesty",
  "has bad judgment!",
  "failing",
  "a fool",
  "so dishonest in his reporting",
  "crazy",
  "an outrage",
  "will soon be the least trusted name in news",
  "not much of a reformer",
  "a zero",
  "pathetic",
  "selling out!",
  "a total embarrassment to himself and his family",
  "fired like a dog!",
  "no STAR",
  "lying",
  "bad television!",
  "highly overrated",
  "no strength, no stamina",
  "wouldn't know the truth if it hit him in the face",
  "has to team up with a guy who openly can't stand him",
  "failing",
  "my judicial appointments will do the right thing unlike... Roberts",
  "totally incompetent as a manager and leader",
  "totally dishonest",
  "lies",
  "already proven FALSE",
  "get your facts straight",
  "his lying is getting worse",
  "incapable of doing anything.",
  "a seriously failing paper",
  "doesn't know how to win",
  "boring",
  "a mixed up man who doesn't have a clue. No wonder he lost!",
  "his record = BAD",
  "he has no sense of the real world!",
  "crime and killing machine",
  "dwindling subscribers and readers",
  "hypocrite",
  "never made ten cents",
  "off the wall",
  "not very bright",
  "a man with so little touch for politics",
  "the most overrated anchor",
  "wrote letter to me begging for forgiveness",
  "bad at math, nobody cares what they say in their editorials anymore, especially me!",
  "serious haters",
  "may poison the minds of the American Voter",
  "no chance",
  "failed policies",
  "a very weak Senator",
  "dishonest",
  "underachieving",
  "not qualified",
  "a total waste of time",
  "crazy and very dumb",
  "losing all credibility",
  "stupidity",
  "terrible",
  "have gotten it wrong for two years",
  "a total meltdown with their FAKE NEWS",
  "the lightweight no show Senator from Florida, just another Washington politician",
  "does too many TV commercials – boring",
  "disgusting",
  "failing",
  "terrible",
  "no more Bushes",
  "making up phony polls in order to suppress the the Trump",
  "low ratings",
  "one of the least effective Senators in the entire U.S. Senate",
  "reported 'Cruz momentum' but nothing about the fact that I easily won!",
  "good for Mexico!",
  "losing big",
  "phony",
  "wants $120,000 to make a boring speech",
  "bad judgment",
  "puppets",
  "being rigged by the media, in a coordinated effort with the Clinton campaign",
  "will allow anyone into the country",
  "will be overturned!",
  "should respect me",
  "got fired like a dog from RedState",
  "won't even call it what it is - RADICAL ISLAM!",
  "they continue to cover me inaccurately and with a nasty tone!",
  "clown announcers",
  "rigged",
  "fraud",
  "made fool of himself in '12",
  "terrible",
  "doesn't have what it takes",
  "phony",
  "fear-mongering!",
  "perhaps the worst president in the history of the United States!",
  "part of the Republican Establishment problem",
  "lies",
  "the man who ‘choked’ and let us all down",
  "low ratings",
  "one of the dumber bloggers",
  "has been largely forgotten",
  "really poor numbers",
  "failing",
  "broken down",
  "corrupt political machine",
  "so biased",
  "totally rigged",
  "terrible today on Face the Nation",
  "dummy",
  "a clown",
  "out of self preservation, is concerned w/ my high poll #s",
  "spending $millions on ads paid for by his N.Y. bosses",
  "biased",
  "sad sack",
  "can't even defend his own microphone",
  "unwatchable",
  "so totally wrong on transition",
  "said horrible things about my supporters",
  "just not getting there",
  "failing",
  "can't get a job!",
  "bad messenger for estab!",
  "is always complaining about Trump and yet she devotes her shows to me",
  "lazy",
  "no more Bushes",
  "the most inaccurate coverage constantly",
  "let us all down in the last presidential race",
  "lies",
  "choked like a dog",
  "asked me for expensive hotel rooms",
  "boring and totally biased",
  "a fraud",
  "dopey",
  "a bush plant who called all races wrong",
  "doing many bad things behind our backs",
  "he has accomplished absolutely nothing",
  "crooked",
  "still doesn't get it",
  "has gone nuts",
  "never discuss the real message",
  "are totally ineffective & have been for years",
  "thugs",
  "worst voting record in the U.S. Senate in many years",
  "has a nasty mouth",
  "failing",
  "really dumb but record setting",
  "just can't get it right!",
  "unfit to serve as President",
  "really dishonest",
  "dumb",
  "all talk, no action",
  "failing",
  "totally biased",
  "sad",
  "need money fast",
  "major lightweight with no credibility",
  "has lost his energy and his strength",
  "dishonest",
  "spent a fortune of special interest money on a Super Bowl ad",
  "dopey writer",
  "dropping like a rock",
  "low ratings!",
  "fake news",
  "crooked",
  "incompetence of our current administration is beyond comprehension",
  "worst show in Las Vegas",
  "a fraud!",
  "crooked",
  "has knowingly committed fraud",
  "unfit to run",
  "falling apart",
  "seldom has a paper been so wrong",
  "not very presidential",
  "pushing the FALSE narrative that I want to raise taxes",
  "has gone wild with hate",
  "very unethical",
  "a total loser!",
  "dishonest",
  "really dumb puppet",
  "the worst",
  "dishonest",
  "can't make a deal work",
  "so off",
  "bad",
  "we get the killers, drugs & crime, they get the money!",
  "failing",
  "attacked New Yorkers and New York values- we don't forget!",
  "dopey",
  "decision making ability-zilch!",
  "unwatchable!",
  "desperate",
  "should immediately apologize to Mike Pence for their terrible behavior",
  "wants to flood our country with Syrian immigrants that we know little or nothing about",
  "a failed 'Bushy' & PA Governor",
  "dopey",
  "doesn't have a clue",
  "incompetent",
  "terrible",
  "dopey clown",
  "not nice",
  "has abandoned his supporters",
  "seriously failing",
  "big tax shelter",
  "false, malicious & libelous",
  "ultra liberal",
  "terrible",
  "looks odd",
  "dishonest reporting",
  "very biased",
  "doing really poorly",
  "a total loser",
  "guilty as hell",
  "low energy",
  "poor work ethic!",
  "rigged",
  "doesn't have a natural instinct for politics",
  "lyin'",
  "on a new phony kick about my management style",
  "dishonest reporting",
  "using the woman’s card",
  "so totally wrong",
  "losing thousands of subscribers because of their very poor and highly inaccurate coverage of the Trump phenomena",
  "zero communication skills",
  "losing lots of money",
  "exhausted",
  "looks more like a gym rat than a U.S. Senator",
  "he came in dead last",
  "would speak behind my back, get caught, and then deny it",
  "total fool",
  "bad reporter",
  "has lost almost all of it's former allure!",
  "worst deal in US history",
  "should be ashamed of himself",
  "a liar!",
  "did an absolutely horrible job of securing the border",
  "dopey",
  "low-life",
  "thugs",
  "always seems to be crying",
  "the worst liar, crazy or very dishonest",
  "job killing",
  "totally biased",
  "has to get his delegates from the Republican bosses",
  "has only created jobs at the FBI and DOJ!",
  "can't win with the voters so he has to sell himself to the bosses",
  "he just wants to shut down and go home to bed!",
  "lightweight",
  "endorsement means nothing!",
  "will drop like a rock in the polls",
  "the Clinton News Network",
  "does not cover me accurately",
  "dishonest",
  "not read or respected by many",
  "just doesn't have IT!",
  "can't win!",
  "lies",
  "phony",
  "weak",
  "should be fired!",
  "liberal clown",
  "don't know how to win",
  "a total clown",
  "lightweight",
  "totally rigged and corrupt!",
  "low life",
  "too soft",
  "phony",
  "never even shows up to vote",
  "portrayal stinks",
  "rigged",
  "one of the dumbest political pundits on television",
  "email lies",
  "has been formally PUT ON NOTICE",
  "money-losing",
  "people don't like",
  "fell right into President Obama's trap on ObamaCare",
  "why can't they get it right",
  "in love with Marco Rubio?",
  "rigged",
  "killing Meet the Press",
  "dummy!",
  "lightweight",
  "weak and ineffective",
  "failed Senator",
  "puppet",
  "stop wasting time and energy on nonsense",
  "so-called judge",
  "no longer has credibility",
  "so disgusting in their bias",
  "the worst",
  "allows dishonest writers to totally fabricate stories",
  "has paid ZERO respect to the great police and law enforcement professionals",
  "doesn't understand what the word demagoguery means",
  "failing",
  "weak & ineffective",
  "clown",
  "worst attendance record in Senate",
  "poorly run and managed",
  "lied",
  "did a terrible job of ticket distrbution",
  "wrong about me from the very beginning",
  "low-level degenerates",
  "losers",
  "lyin'",
  "horrible",
  "losing for years",
  "disloyal person",
  "dopey",
  "not as smart as Cruz, and may be an even bigger liar",
  "should never have been written",
  "failing",
  "just doesn't get it",
  "perhaps the worst president in U.S. history!",
  "boring guy",
  "not very good or professional",
  "a lightweight",
  "failed image",
  "has totally given up on his fight for the people",
  "pure scum",
  "mental basketcase",
  "not being honored",
  "some very untalented reporters",
  "totally sold out",
  "another all talk, no action pol!",
  "dopey",
  "has never created a job in her life",
  "wrong almost all of the time",
  "ending really weak",
  "poor",
  "in the bag!",
  "never covered Hillary's massive hacking or coughing attack",
  "failing",
  "panels are so one sided",
  "trying to destroy Israel with all his bad moves",
  "a major sleaze and buffoon",
  "dope",
  "clowns",
  "opens up our country to potential terrorists and others that do not have our best interests at heart",
  "pushing the GOP around",
  "will be soundly defeated",
  "thugs",
  "many lies by Ben Carson",
  "so inappropriate",
  "just another all talk, no action, politician",
  "dope",
  "should take another eleven day 'unscheduled' vacation",
  "such bad reporting",
  "dopey",
  "goofy",
  "circulation dropping to record lows",
  "loves to lie",
  "reckless and dangerous",
  "dopey",
  "so biased it is disgusting",
  "ridiculous",
  "will NEVER be able to solve the problems of poverty, education and safety",
  "very insecure",
  "has gone nasty with lies",
  "failing",
  "corrupt",
  "campaign is a disaster",
  "phony",
  "was a major security risk",
  "not looking smart",
  "a mess",
  "lied",
  "very disloyal company",
  "dummy",
  "looks like a little boy on stage",
  "so easy to beat!",
  "is still lost!",
  "did a 1 hour hit job on me today",
  "illegally put out a fundraising notice saying Trump wants you to contribute to the RNC",
  "dying",
  "failing",
  "so dishonest!",
  "unbelievable corruption",
  "should not be allowed on TV",
  "continues to report fictious poll numbers",
  "fraud lightweight",
  "failing, crying, lost soul",
  "not qualified!",
  "they have lost their way and are no longer credible",
  "you never speak well of me & yet when I saw you at Fox you ran over like a child and wanted a picture",
  "purposely mischaracterized my statement",
  "tried to shake me down for one million dollars",
  "total low life",
  "little watched",
  "dishonest",
  "totally confused",
  "one of the most over-rated actresses in Hollywood",
  "should not make statements behind closed doors to his bosses",
  "distorted",
  "failing",
  "fraudulent story",
  "a fraud",
  "broken, like so much else in our country",
  "so average in every way",
  "failed, poorly rated",
  "ever-dwindling",
  "nasty to Sanders supporters behind closed doors",
  "considered by many in the world of politics to be the dumbest and most slanted of the political sites",
  "failing",
  "too much staff being paid way too much money",
  "look at all of the bad decisions she has made",
  "totally rigged!",
  "reminds me of a spoiled brat without a properly functioning brain",
  "don't watch her show",
  "doesn't even look presidential!",
  "a disgusting fraud",
  "has been involved in corruption for most of her professional life!",
  "did a terrible job",
  "will be dead in 2 years",
  "spending more time doing a forensic analysis of Melania's speech than the FBI spent on Hillary's emails",
  "biased",
  "unfair",
  "disastrous",
  "totally biased loser who doesn't have a clue",
  "is being rigged",
  "totally one-sided interview",
  "unwatchable",
  "all talk and no action",
  "dummy",
  "so careless",
  "so totally biased",
  "not presidential material!",
  "dishonest",
  "policies in Florida helped lead to its almost total collapse",
  "does not have the STRENGTH or STAMINA to be President",
  "lied",
  "phony Native American heritage",
  "corrupt",
  "a real dope",
  "failed campaign",
  "was a lie from the beginning",
  "not at all loyal",
  "dumb",
  "a big mistake",
  "thugs",
  "dishonest",
  "campaign is a disaster",
  "made many bad calls",
  "was called a racist",
  "terrible at business",
  "taking the day off again, she needs the rest",
  "few people know that Fortune Magazine is still in business",
  "rarely there to vote on a bill",
  "desperate",
  "in total disarray",
  "dishonest",
  "lightweight",
  "money losing",
  "failing",
  "they don't appreciate how kind President Obama was to them. Not me!",
  "highly overrated",
  "incompetent",
  "worst voting record in Sen.",
  "so average in so many ways!",
  "we are all tired [of them]",
  "a total phony and con man",
  "bad judgment",
  "a disaster",
  "has no power in Iowa",
  "totally corrupt",
  "biased dope",
  "lightweight",
  "has very small and unenthusiastic crowds in Pennsylvania",
  "always looking for a hit to bring them back into relevancy—ain't working",
  "a cheater!",
  "suffers from plain old bad judgement!",
  "how the hell did he ever get elected?",
  "very boring and low rated show",
  "totally discredited",
  "desperate move by the man who should have easily beaten Barrack Obama",
  "suffers from BAD JUDGEMENT!",
  "just doesn't get it",
  "irresponsible intent",
  "getting ready to treat me unfairly",
  "made all bad decisions over the last decade",
  "incompetent",
  "unfair",
  "failing",
  "unqualified to be president",
  "pathetic",
  "a very weak and ineffective Senator",
  "all talk and no action",
  "really dumb puppet",
  "totally in the Hillary circle of bias",
  "should be ashamed of herself",
  "treated America's ICE officers 'like absolute trash' in order to pass Obama's amnesty",
  "wacky",
  "the Republican Convention was far more interesting (with a much more beautiful set)",
  "pathetic",
  "let us down",
  "weak & ineffective",
  "our country needs more energy and spirit than you can provide!",
  "terrible",
  "won't survive",
  "failing",
  "failing",
  "terrible on Face the Nation",
  "bad!",
  "the most overrated person on tv",
  "living in a world of the make believe!",
  "just a 3rd rate 'gotcha' guy!",
  "great people being disenfranchised by politicians. Repub party is in trouble!",
  "will be out!",
  "a big problem!",
  "obnoxious",
  "absolutely being rigged",
  "has never created a job in his life (well, maybe a nurse)",
  "spent $59 million & done",
  "biased",
  "failed campaign strategist",
  "stupid message",
  "really on a witch-hunt against me",
  "sooooo guilty",
  "went hostile",
  "dopey",
  "judgement has killed thousands, unleashed ISIS and wrecked the economy",
  "failed",
  "the ultimate hypocrite",
  "a joke!",
  "one of the least productive U.S. Senators",
  "not looking good",
  "has done nothing!",
  "lightweight",
  "the least productive Senator in the U.S. Senate",
  "allowed Crooked Hillary to get away with 'murder'",
  "truly weird",
  "very gentle and soft",
  "lightweight",
  "distorted",
  "angry haters",
  "ratings starved",
  "making up stories & sources!",
  "lied to the FBI and to the people of our country",
  "so awkward and goofy",
  "one of the least productive senators",
  "has zero cred",
  "they're killing us",
  "a total Clinton flunky!",
  "a scam!",
  "really bad",
  "hollowing out our military",
  "will NEVER be able to handle the complexities and danger of ISIS",
  "lies",
  "has embarrassed all by making very dumb political statements about me",
  "bad reporter",
  "doing a terrible job",
  "nobody reads it",
  "a waste",
  "puppet",
  "will not report the highly respected new national poll that just came out",
  "very rude",
  "big help will be needed fast",
  "failing",
  "weak on illegal immigration",
  "put together a hit job book on me",
  "dead T.V.",
  "covers me so inaccurately",
  "had a mental breakdown while talking about me",
  "a total disaster",
  "no solutions, no ideas, no credibility",
  "owned by the banks",
  "poor",
  "has done such a complete fold",
  "very boring",
  "complete & total liar",
  "wacko",
  "bad",
  "rambling, overly flamboyant",
  "totally biased and disgusting reporting",
  "a highly overrated politician",
  "just lied again",
  "one of the least talented people on television",
  "ratings are tanking since election",
  "phony Native American heritage",
  "so totally biased",
  "failing",
  "embarrassed herself and the country with her e-mail lies",
  "failing",
  "they only want negatives",
  "a small group of people who have suffered massive and embarrassing losses",
  "flunkie",
  "negative ads are not TRUE",
  "set to be the 'puppet' of the special interest Koch brothers",
  "has such great potential but right now it is just a club for people to get together, talk and have a good time",
  "the trade deal is a disaster, she was always for it!",
  "a dumb guy who fails @ virtually everything he touches",
  "totally biased and mostly FALSE",
  "goofy",
  "did such a horrible job",
  "beg for money etc. from the Koch Brothers",
  "couldn't get elected dog catcher",
  "illegally circulated",
  "took millions of $'s of hit ads on me",
  "the WTC came down during his watch",
  "loser",
  "the Cruz people are back to doing very sleazy and dishonest 'pushpolls' on me",
  "totally dishonest!",
  "horrible",
  "there are far better stores",
  "change your FALSE story",
  "lowly",
  "a dope",
  "even dumber",
  "called African-American youth SUPER PREDATORS",
  "begged me for ads",
  "people do not like Ted",
  "scam to fill up their coffers",
  "so FALSE and angry",
  "a clown with zero credibility",
  "totally one-sided and biased against me that it is becoming boring",
  "totally rigged & corrupt!",
  "phony",
  "owned by Wall Street!",
  "a puff piece",
  "has no chance!",
  "should be fired",
  "what the other candidates are doing is a disgrace",
  "does not have the right 'temperment' to be President",
  "cratered",
  "dangerous",
  "failed",
  "always looking to start World War III",
  "doesn't have a clue!",
  "has ZERO credibility",
  "total frauds",
  "has zero chance",
  "are spending $25 million on misleading and fraudulent T.V. ads on me",
  "so sad",
  "desperate",
  "pathetic",
  "very bad judgement",
  "goofy",
  "rigged",
  "incompetent",
  "failed campaign manager of Mitt Romney's historic loss",
  "took hundreds of thousands of dollars in gifts",
  "circulation way down",
  "totally one-sided spin",
  "lightweight",
  "ridiculous",
  "third-rate-reporter",
  "a mess",
  "horrible",
  "the real predators",
  "will fall of its own weight",
  "incapable of understanding foreign policy",
  "failed",
  "lost all credibility",
  "upset that they looked like fools in their coverage of me",
  "the system is rigged",
  "all talk and NO ACTION!",
  "boring articles",
  "worst voting record in Senate",
  "truly doesn't have a clue!",
  "going out of business",
  "incoherent with anger",
  "failing",
  "perhaps the most dishonest person to have ever run for the presidency",
  "a joke",
  "never even call to fact check",
  "his predictions are always wrong",
  "media-rigged",
  "he should go home and relax!",
  "close to death",
  "kooky",
  "low-energy 'stiff'",
  "no focus, poor level of concentration",
  "horribly negotiated",
  "dishonest",
  "his last term as Mayor was a disaster!",
  "ruining Germany",
  "just another Washington D.C. politician",
  "distorted and inaccurate",
  "dopey",
  "one of the most boring, rambling and non-substantive I have heard in a long time",
  "dishonest",
  "pushing FALSE and unsubstantiated charges, and outright lies",
  "such bad judgement",
  "choker",
  "totally biased",
  "brainpower is highly overrated, decision making is so bad",
  "failing",
  "has failed miserably",
  "@washingtonpost scam is saving it!",
  "needs a new pair of glasses",
  "has become a joke!",
  "wasted a lot of time and money",
  "rigged",
  "dying tabloid",
  "obsolete",
  "not caring for the truth",
  "mere puppets",
  "has lost its way!",
  "shouldn't be allowed to do [his] bias commentary",
  "dummy",
  "failing",
  "a totally one-sided, biased show - nothing funny at all",
  "really stupid talking head",
  "everyone knows they are biased",
  "is miserable",
  "delaying my cabinet picks for purely political reasons",
  "gets worse and worse by the day",
  "lightweight",
  "grubby",
  "asked me for $1 million. I said no & they went negative. Extortion!",
  "defrauded America",
  "begged for my support during his primary (I gave, he won)",
  "was going off the air until I came along",
  "typically FALSE",
  "didn't show his tax return until SEPTEMBER 21, 2012, and then only after being humiliated by Harry R",
  "not good",
  "unethical record",
  "disaster!",
  "totally distort so many things on purpose",
  "low-energy individual",
  "weak",
  "incorrect story",
  "all negative when it comes to me",
  "greatly dishonest",
  "puppet!",
  "totally biased against me",
  "a real nut job",
  "had her two puppets say bad stuff",
  "won't call out radical Islam",
  "not getting the job done",
  "just hopeless",
  "didn’t have the guts to run for POTUS",
  "very weak",
  "lost his way long ago",
  "failing",
  "very boring",
  "doesn't have a clue",
  "doesn't have the drive or stamina to MAKE AMERICA GREAT AGAIN!",
  "money losing",
  "lies!",
  "gets nothing done",
  "bought and paid for by Wall Street, lobbyists and special interests",
  "low-rated",
  "will lose readers!",
  "doing so badly compared to its glorious past",
  "only writes dishonest hits!",
  "very sad!",
  "really dumb",
  "didn't win Iowa, he illegally stole it",
  "wants to control our U.S. politicians with daddy's money",
  "a divided crime scene",
  "turns everyone off",
  "never liked",
  "just made up lies!",
  "one of the most overrated political pundits",
  "does zilch!",
  "can't get votes (I am millions ahead of him)",
  "failed",
  "mathematically dead and totally desperate",
  "no honor!",
  "knows nothing about finance",
  "dishonest",
  "disgrace",
  "rigged",
  "will be a disaster",
  "let us down",
  "not good reporting",
  "failed campaign & debating skills",
  "wasting time & money",
  "the worst economic deal in U.S. history",
  "no one has worse judgement",
  "weak",
  "racial profiling",
  "so biased",
  "will sell our country down the tubes!",
  "sleazebag",
  "mathematically dead and totally desperate",
  "bad management",
  "really off her game",
  "his proposal was a rip off",
  "very dumb",
  "very disloyal to Jeb",
  "he is a choker, and once a choker, always a choker!",
  "the lightweight from Florida",
  "bombed last night!",
  "will be fired like a dog",
  "a sad case",
  "total mess",
  "so dishonest",
  "1 CONTROLLED",
  "disastrous",
  "rigging election!",
  "virtually incompetent",
  "sleepy eyes",
  "lost it's way",
  "failed presidential candidate",
  "bad judgement",
  "made some of the dumbest political decisions of all time",
  "ridiculous debate terms",
  "fraudulent",
  "try hiring some good managers",
  "hardly knows me",
  "wants to surrender constitutional rights",
  "puppet",
  "dope",
  "ultra liberal",
  "went hostile w/ a series of incorrect & ill-informed ads",
  "a disaster",
  "sleepy eyes",
  "control our politicians (puppets)",
  "unfit to be president",
  "horrendous",
  "weak",
  "always looking to start World War III",
  "not nice!",
  "once a choker, always a choker!",
  "a loser",
  "get tough and smart U.S., or we won't have a country anymore",
  "so dishonest",
  "flunkie",
  "dopey",
  "told thousands of caucusgoers (voters) that Trump was strongly in favor of ObamaCare and 'choice' - a total lie!",
  "a formula for disaster!",
  "can't close the deal on Crazy Bernie",
  "not a nice person!",
  "dishonest",
  "clown",
  "has done nothing",
  "failed writer",
  "hater & racist",
  "go out of their way to distort truth!",
  "stupid",
  "able to so incorrectly define a word for the public",
  "ineffective",
  "little watched",
  "has deceived the public by putting women front and center with made-up stories and lies",
  "getting more and more biased",
  "troublemakers",
  "low ratings",
  "a total mess-big crime",
  "very dishonest",
  "mostly losers in life!",
  "isn't smart enough to know what's going on at the border",
  "even dumber",
  "failing",
  "the worst mayor in the United States",
  "lied",
  "a hostile basket case who feels jilted!",
  "can never beat Hilary Clinton",
  "a clown",
  "knows nothing about me",
  "paid a fortune for an Iowa Poll, which shows me in first place over Cruz by 13%, 0.33 to 0.2 - then doesn't use it",
  "a disaster",
  "dishonest",
  "a loser",
  "small and slightly failing magazine",
  "trying hard to disguise their massive Muslim problem",
  "one of the dumbest and worst candidates in the history of Republican politics",
  "unfit to be president",
  "a disaster!",
  "has NO path to victory",
  "makes up things that I never said",
  "has been confused for forty years",
  "perfect little puppet",
  "irrelevant",
  "deceptive",
  "such a mess",
  "failing",
  "spends so much time speaking of the so-called Carbon footprint, and yet he flies all the way to Hawaii on a massive old 747",
  "no 'it' factor",
  "3rd rate reporter",
  "campaign is a disaster",
  "falsely advertising",
  "low ratings",
  "so dishonest",
  "failed presidential candidate",
  "ratings are so low - and getting worse",
  "terrible hypocrites",
  "almost dead",
  "out of control",
  "very hard to watch",
  "lied last week",
  "very dishonest",
  "just doesn't work",
  "experts in never facing any consequence",
  "very long and very boring speech",
  "failing campaign",
  "so negative",
  "lightweight",
  "should be focused on good reporting and the papers financial survival",
  "questioned me in such a nasty fashion",
  "lyin'",
  "has lost statewide 7 times in a row",
  "has been so wrong & he hates it!",
  "a nasty guy",
  "has very little chance",
  "graduated last in his class",
  "third-rate-reporter",
  "failing",
  "everyone of those people who contributed are getting something to the detriment of America",
  "highly overrated",
  "moron",
  "too weak to lead",
  "at the bottom of the barrel",
  "one big lie!",
  "phony",
  "doesn't have a clue",
  "lousy",
  "dishonest",
  "totally unfit to be our president",
  "dummy",
  "very dishonest",
  "incompetent",
  "launched her political career by letting terrorists off the hook",
  "not a fan",
  "didn't love it",
  "without me they'd have no ratings!",
  "total failure",
  "failing",
  "didn't win one race",
  "not very bright",
  "bad product",
  "should be thrown off Fox News",
  "dishonest reporters!",
  "know nothing",
  "a toy by comparison",
  "a crude dope!",
  "very bad",
  "totally rigged",
  "she doesn’t have a clue",
  "in the end he had no support",
  "a total scam on our system and country",
  "very dishonest",
  "the WORST abuser of woman in U.S. political history",
  "wanted V.P. slot so badly but wasn't chosen because she has done nothing in the Senate",
  "the loss by the Dems was so big",
  "a disaster",
  "incapable of making great trade deals",
  "dopey political pundit",
  "money-losing",
  "they don't have a clue!",
  "should change their fraudulent story",
  "very unfair",
  "there's never been anything like your lies",
  "your very dumb fundraiser hit me very hard--- not smart!",
  "nothing going but to obstruct",
  "a failed Jeb Bushy",
  "faulty thought process",
  "failing",
  "wacko",
  "got thrown off of TV by NBC",
  "clown",
  "worthless",
  "zero natural talent",
  "total fraud!",
  "poorly defended",
  "he choked!",
  "disgusting",
  "dishonest",
  "will never secure the border",
  "total loser",
  "never been able to make a comeback",
  "treats me so badly",
  "a total lie",
  "one hour of lies",
  "looking for a new puppet",
  "terrible!",
  "a clown",
  "nothing Hillary has said about her secret server has been TRUE",
  "loses a fortune",
  "corruption is what she's best at",
  "failing",
  "dead",
  "why would anybody listen to @MittRomney?",
  "flamed out",
  "temperament is bad",
  "joke of a deal",
  "dopey",
  "dishonest",
  "copying my airplane rallies",
  "had a tiny 300 person crowd",
  "terrible ratings",
  "1 made up",
  "ineffective",
  "failing",
  "lightweight choker",
  "third rate reporter",
  "highly overrated",
  "broken down political pundit",
  "did the phony election polls",
  "a liar!",
  "lies like a dog-over and over again!",
  "a disaster",
  "lightweight Senator",
  "bad judgment",
  "holds the Bible high and then lies and misrepresents the facts!",
  "he is just so bad!",
  "now in total freefall",
  "should change their fraudulent story",
  "lightweight",
  "no profit company",
  "dope",
  "pretends she knows me well--wrong!",
  "corruption and devastation follows her",
  "spending a fortune of special interest against me in SC",
  "bought and paid for by lobbyists!",
  "bombed",
  "boring interviews and column",
  "dumb mouthpiece",
  "totally controlled",
  "total hypocrite",
  "should be defeated in the primaries",
  "failing",
  "dummy",
  "dishonest reporting",
  "has not reported properly",
  "not fair",
  "disgusting (check out sex tape and past)",
  "totally out of control",
  "goofball atheist",
  "rigged",
  "in a total meltdown",
  "should be in jail",
  "terrible governor of NY, one of the worst",
  "corrupt",
  "failing so badly that it will soon be taken off thr air",
  "suicidal",
  "costs are out of control",
  "disloyal",
  "consistently fumbles & misrepresents poll results",
  "all negative",
  "a third rate talent",
  "pushing Republicans down the same old path of defeat",
  "low energy guy",
  "looking so dumb",
  "stupid",
  "rigged",
  "failing",
  "weak",
  "phony",
  "disaster",
  "working hard to make me look as bad as possible",
  "has gotten worse and worse",
  "it will only get worse!",
  "fired from her last show for lack of ratings",
  "no more Bushes",
  "should have gone to prison",
  "extraordinarily bad judgement & insticts",
  "a loser",
  "a joke!",
  "very dishonest",
  "clown",
  "not presidential material",
  "bad ratings",
  "should be ashamed of himself",
  "never had a chance",
  "[one] of the dumbest people in politics",
  "unfair",
  "a dumb group!",
  "made-up",
  "lightweight reporter",
  "sadly weak on immigration",
  "totally flawed candidate",
  "should be fired",
  "try to belittle our victory with FAKE NEWS",
  "totally unelectable",
  "hypocrite",
  "biased",
  "highly unethical",
  "dishonest",
  "dumb guy with no clue",
  "thugs",
  "only puts negative people on",
  "kicked out of the ABC news debate like a dog",
  "very incompetent",
  "falling in the polls",
  "a total disaster",
  "dummy",
  "all he can do is be a spoiler, never a nice thing to do",
  "failed",
  "deadpan",
  "3rd rate $ losing",
  "dishonest",
  "got me wrong right from the beginning and still have not changed course, and never will",
  "unfit to lead the country",
  "such bad judgement",
  "wacky",
  "doesn’t have a clue",
  "terrible 'choke' loss to Obama",
  "bad",
  "dishonest",
  "totally dishonest",
  "pushing the FALSE narrative that I want to raise taxes",
  "totally dishonest",
  "very dishonest",
  "in pocket of Wall Street",
  "incompetent leader",
  "terrible",
  "will always take a good story about me and make it bad",
  "can't debate",
  "terrible political instincts",
  "perv",
  "hates New York",
  "hokey garbage",
  "very bad and destructive track record",
  "why did they not have 'hacking defense' like the RNC has",
  "very disloyal to me",
  "writes total fiction concerning me",
  "no enthusiasm!",
  "only won the debate in the minds of desperate people",
  "did a terrible job",
  "has been treating me very unfairly",
  "without us, gone!",
  "begging for money like a dog",
  "reporting is terrible & highly inaccurate",
  "spent $1,000 to register in New Hampshire & dropped out the next day. Such a waste!",
  "lightweight",
  "rigged!",
  "one big lie!",
  "bad and inaccurate coverage of me",
  "cheater",
  "trying their absolute best to depict a star in a tweet as the Star of David rather than a Sheriff's Star, or plain star!",
  "bad judgement",
  "has lost all credibility",
  "a bad guy!",
  "goofy couldn’t care less about the American worker",
  "very dumb and failing",
  "a lose cannon",
  "weak understanding of weapons of mass destruction in Iraq",
  "dummy",
  "crazy",
  "a laughingstock rag!",
  "no guts, no glory",
  "dying",
  "very weak on illegal immigration",
  "totally biased against me",
  "failed campaign",
  "will fade fast",
  "a big failure in TV",
  "will do anything to stay at the trough",
  "only looks O.K. in polls against Hillary because nobody views him as a threat and therefore have placed ZERO negative ads against him",
  "not qualified",
  "doesn't have the strength or stamina to be president",
  "not smart",
  "treats me very badly",
  "failing",
  "failing",
  "no honor!",
  "crying",
  "has no talent, no TV persona",
  "her judgement has been proven to be so bad!",
  "knows so little about politics",
  "embarrasses himself with endorsement of Bush",
  "has become a dumping ground for the world",
];
